let MersenneTwisterFast;

(function(){
'use strict';var h;Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.13.0",fileLevelThis:this});var aa;function ba(a){for(var b in a)return b}function l(a){this.lb=a}l.prototype.toString=function(){return String.fromCharCode(this.lb)};var da=function ca(a,b,c){var e=new a.$(b[c]);if(c<b.length-1){a=a.Z;c+=1;for(var f=e.a,g=0;g<f.length;g++)f[g]=ca(a,b,c)}return e};
function ea(a){switch(typeof a){case "string":return n(fa);case "number":return ha(a)?a<<24>>24===a?n(ia):a<<16>>16===a?n(ja):n(ka):la(a)?n(ma):n(na);case "boolean":return n(oa);case "undefined":return n(pa);default:return null===a?a.fc():a instanceof p?n(qa):a instanceof l?n(ra):a&&a.$classData?n(a.$classData):null}}
function sa(a){switch(typeof a){case "string":return"java.lang.String";case "number":return ha(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":la(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.fc():a instanceof p?"java.lang.Long":a instanceof l?"java.lang.Character":a&&a.$classData?a.$classData.name:null.ba.name}}
function ta(a,b){switch(typeof a){case "string":return a===b;case "number":return Object.is(a,b);case "boolean":return a===b;case "undefined":return a===b;default:return a&&a.$classData||null===a?a=a.B(b):a instanceof p?b instanceof p?(b=q(b),a=a.i===b.i&&a.l===b.l):a=!1:a=a instanceof l?b instanceof l?r(a)===r(b):!1:t.prototype.B.call(a,b),a}}
function ua(a){switch(typeof a){case "string":return u(a);case "number":return va(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.y():a instanceof p?a.i^a.l:a instanceof l?r(a):t.prototype.y.call(a)}}function wa(a,b){if(0===b)throw new xa;return a%b|0}function ya(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}var za=0,Aa=new WeakMap;
function Ba(a){switch(typeof a){case "string":return u(a);case "number":return va(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:u(a);default:if(null===a)return 0;b=Aa.get(a);void 0===b&&(za=b=za+1|0,Aa.set(a,b));return b}}function ha(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}
function la(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function r(a){return null===a?0:a.lb}function q(a){return null===a?aa:a}function t(){}t.prototype.constructor=t;function v(){}v.prototype=t.prototype;t.prototype.y=function(){return Ba(this)};t.prototype.B=function(a){return this===a};t.prototype.r=function(){var a=this.y();return sa(this)+"@"+(+(a>>>0)).toString(16)};t.prototype.toString=function(){return this.r()};
function w(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}w.prototype=new v;w.prototype.constructor=w;w.prototype.x=function(){return new w(this.a.slice())};function Ca(){}Ca.prototype=w.prototype;function Da(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}Da.prototype=new v;Da.prototype.constructor=Da;Da.prototype.x=function(){return new Da(this.a.slice())};
function Ea(a){this.a="number"===typeof a?new Uint16Array(a):a}Ea.prototype=new v;Ea.prototype.constructor=Ea;Ea.prototype.x=function(){return new Ea(this.a.slice())};function Fa(a){this.a="number"===typeof a?new Int8Array(a):a}Fa.prototype=new v;Fa.prototype.constructor=Fa;Fa.prototype.x=function(){return new Fa(this.a.slice())};function Ga(a){this.a="number"===typeof a?new Int16Array(a):a}Ga.prototype=new v;Ga.prototype.constructor=Ga;Ga.prototype.x=function(){return new Ga(this.a.slice())};
function x(a){this.a="number"===typeof a?new Int32Array(a):a}x.prototype=new v;x.prototype.constructor=x;x.prototype.x=function(){return new x(this.a.slice())};function Ha(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=aa}else this.a=a}Ha.prototype=new v;Ha.prototype.constructor=Ha;Ha.prototype.x=function(){return new Ha(this.a.slice())};function Ia(a){this.a="number"===typeof a?new Float32Array(a):a}Ia.prototype=new v;Ia.prototype.constructor=Ia;Ia.prototype.x=function(){return new Ia(this.a.slice())};
function Ja(a){this.a="number"===typeof a?new Float64Array(a):a}Ja.prototype=new v;Ja.prototype.constructor=Ja;Ja.prototype.x=function(){return new Ja(this.a.slice())};function z(){this.$=void 0;this.X=this.Z=this.p=null;this.Y=0;this.Yb=null;this.L="";this.N=this.U=this.Ga=void 0;this.name="";this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}
function A(a,b,c,d){var e=new z;e.p={};e.Yb=a;e.L=b;e.N=f=>f===e;e.name=c;e.isPrimitive=!0;e.isInstance=()=>!1;void 0!==d&&(e.U=Ka(e,d));return e}function C(a,b,c,d){var e=new z,f=ba(a);e.p=c;e.L="L"+b+";";e.N=g=>!!g.p[f];e.name=b;e.isInterface=!1;e.isInstance=d||(g=>!!(g&&g.$classData&&g.$classData.p[f]));return e}
function Ka(a,b,c){var d=new z;b.prototype.$classData=d;var e="["+a.L;d.$=b;d.p={c:1,Ja:1,d:1};d.Z=a;d.X=a;d.Y=1;d.L=e;d.name=e;d.isArrayClass=!0;d.N=c||(f=>d===f);d.isInstance=f=>f instanceof b;return d}
function La(a){function b(k){if("number"===typeof k){this.a=Array(k);for(var m=0;m<k;m++)this.a[m]=null}else this.a=k}var c=new z;b.prototype=new Ca;b.prototype.constructor=b;b.prototype.x=function(){return new b(this.a.slice())};var d=a.X||a,e=a.Y+1;b.prototype.$classData=c;var f="["+a.L;c.$=b;c.p={c:1,Ja:1,d:1};c.Z=a;c.X=d;c.Y=e;c.L=f;c.name=f;c.isArrayClass=!0;var g=k=>{var m=k.Y;return m===e?d.N(k.X):m>e&&d===D};c.N=g;c.isInstance=k=>{k=k&&k.$classData;return!!k&&(k===c||g(k))};return c}
function Ma(a){a.U||(a.U=La(a));return a.U}function n(a){a.Ga||(a.Ga=new Na(a));return a.Ga}z.prototype.isAssignableFrom=function(a){return this===a||this.N(a)};z.prototype.checkCast=function(){};z.prototype.getSuperclass=function(){return this.Xc?n(this.Xc):null};z.prototype.getComponentType=function(){return this.Z?n(this.Z):null};z.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ma(b);return da(b,a,0)};var D=new z;D.p={c:1};D.L="Ljava.lang.Object;";D.N=a=>!a.isPrimitive;
D.name="java.lang.Object";D.isInstance=a=>null!==a;D.U=Ka(D,w,a=>{var b=a.Y;return 1===b?!a.X.isPrimitive:1<b});t.prototype.$classData=D;A(void 0,"V","void",void 0);A(!1,"Z","boolean",Da);A(0,"C","char",Ea);A(0,"B","byte",Fa);A(0,"S","short",Ga);A(0,"I","int",x);var Oa=A(null,"J","long",Ha);A(0,"F","float",Ia);A(0,"D","double",Ja);
function Pa(){this.qb=this.na=this.ca=null;Qa=this;this.ca=new ArrayBuffer(8);this.na=new Int32Array(this.ca,0,2);new Float32Array(this.ca,0,2);this.qb=new Float64Array(this.ca,0,1);this.na[0]=16909060;new Int8Array(this.ca,0,8)}Pa.prototype=new v;Pa.prototype.constructor=Pa;function Ra(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.qb[0]=b;return(a.na[0]|0)^(a.na[1]|0)}Pa.prototype.$classData=C({qc:0},"java.lang.FloatingPointBits$",{qc:1,c:1});var Qa;
function Sa(){Qa||(Qa=new Pa);return Qa}function Ta(){this.rb=null;Ua=this;this.rb="undefined"!==typeof performance?performance.now?()=>+performance.now():performance.webkitNow?()=>+performance.webkitNow():()=>+(new Date).getTime():()=>+(new Date).getTime()}Ta.prototype=new v;Ta.prototype.constructor=Ta;Ta.prototype.$classData=C({Ac:0},"java.lang.System$NanoTime$",{Ac:1,c:1});var Ua;function Va(){this.oa=null;Wa=this;this.oa=Object.prototype.hasOwnProperty}Va.prototype=new v;
Va.prototype.constructor=Va;Va.prototype.$classData=C({Cc:0},"java.lang.Utils$Cache$",{Cc:1,c:1});var Wa;function Xa(){Wa||(Wa=new Va);return Wa}var pa=C({Dc:0},"java.lang.Void",{Dc:1,c:1},a=>void 0===a);function Ya(){}Ya.prototype=new v;Ya.prototype.constructor=Ya;Ya.prototype.$classData=C({Ec:0},"java.util.Arrays$",{Ec:1,c:1});var Za;function E(a,b){throw new $a(b,a.j,a.b);}function ab(a,b){for(var c="",d=b.length,e=0;e!==d;){var f=bb(b,e);c=""+c+cb(a,f);e=e+(65536<=f?2:1)|0}return c}
function cb(a,b){var c=db(F(),b);if(128>b)switch(b){case 94:case 36:case 92:case 46:case 42:case 43:case 63:case 40:case 41:case 91:case 93:case 123:case 125:case 124:return"\\"+c;default:return 2!==(66&a.e)?c:65<=b&&90>=b?"["+c+db(F(),32+b|0)+"]":97<=b&&122>=b?"["+db(F(),-32+b|0)+c+"]":c}else return 56320===(-1024&b)?"(?:"+c+")":c}
function eb(a){for(var b=a.j,c=b.length;;){if(a.b!==c)switch(b.charCodeAt(a.b)){case 32:case 9:case 10:case 11:case 12:case 13:a.b=1+a.b|0;continue;case 35:fb(a);continue}break}}
function gb(a,b,c){var d=a.j,e=d.length,f=a.b,g=f===e?46:d.charCodeAt(f);if(63===g||42===g||43===g||123===g){switch(c.charCodeAt(0)){case 94:case 36:f=!0;break;case 40:f=63===c.charCodeAt(1)&&58!==c.charCodeAt(2);break;case 92:f=c.charCodeAt(1);f=98===f||66===f;break;default:f=!1}c=f?"(?:"+c+")":c;f=a.j;var k=a.b;a.b=1+a.b|0;if(123===g){g=f.length;if(a.b===g)var m=!0;else m=f.charCodeAt(a.b),m=!(48<=m&&57>=m);for(m&&E(a,"Illegal repetition");;)if(a.b!==g?(m=f.charCodeAt(a.b),m=48<=m&&57>=m):m=!1,
m)a.b=1+a.b|0;else break;a.b===g&&E(a,"Illegal repetition");if(44===f.charCodeAt(a.b))for(a.b=1+a.b|0;;)if(a.b!==g?(m=f.charCodeAt(a.b),m=48<=m&&57>=m):m=!1,m)a.b=1+a.b|0;else break;a.b!==g&&125===f.charCodeAt(a.b)||E(a,"Illegal repetition");a.b=1+a.b|0}f=f.substring(k,a.b);if(a.b!==e)switch(d.charCodeAt(a.b)){case 43:return a.b=1+a.b|0,hb(a,b,c,f);case 63:return a.b=1+a.b|0,""+c+f+"?";default:return""+c+f}else return""+c+f}else return c}
function hb(a,b,c,d){for(var e=a.u.length|0,f=0;f<e;){var g=f,k=a.u[g]|0;k>b&&(a.u[g]=1+k|0);f=1+f|0}c=c.replace(F().Db,(m,y,B)=>{0!==(y.length%2|0)&&(B=parseInt(B,10)|0,m=B>b?""+y+(1+B|0):m);return m});a.t=1+a.t|0;return"(?:(?\x3d("+c+d+"))\\"+(1+b|0)+")"}
function ib(a){var b=a.j,c=b.length;(1+a.b|0)===c&&E(a,"\\ at end of pattern");a.b=1+a.b|0;var d=b.charCodeAt(a.b);switch(d){case 100:case 68:case 104:case 72:case 115:case 83:case 118:case 86:case 119:case 87:case 112:case 80:switch(a=jb(a,d),b=a.Na,b){case 0:return"\\p{"+a.G+"}";case 1:return"\\P{"+a.G+"}";case 2:return"["+a.G+"]";case 3:return kb(F(),a.G);default:throw new lb(b);}case 98:if("b{g}"===b.substring(a.b,4+a.b|0))E(a,"\\b{g} is not supported");else if(0!==(320&a.e))mb(a,"\\b with UNICODE_CASE");
else return a.b=1+a.b|0,"\\b";break;case 66:if(0!==(320&a.e))mb(a,"\\B with UNICODE_CASE");else return a.b=1+a.b|0,"\\B";break;case 65:return a.b=1+a.b|0,"^";case 71:E(a,"\\G in the middle of a pattern is not supported");break;case 90:return a.b=1+a.b|0,"(?\x3d"+(0!==(1&a.e)?"\n":"(?:\r\n?|[\n\u0085\u2028\u2029])")+"?$)";case 122:return a.b=1+a.b|0,"$";case 82:return a.b=1+a.b|0,"(?:\r\n|[\n-\r\u0085\u2028\u2029])";case 88:E(a,"\\X is not supported");break;case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:var e=
a.b;for(d=1+e|0;;){if(d!==c){var f=b.charCodeAt(d);f=48<=f&&57>=f}else f=!1;f?(f=b.substring(e,1+d|0),f=(parseInt(f,10)|0)<=(-1+(a.u.length|0)|0)):f=!1;if(f)d=1+d|0;else break}b=b.substring(e,d);b=parseInt(b,10)|0;b>(-1+(a.u.length|0)|0)&&E(a,"numbered capturing group \x3c"+b+"\x3e does not exist");b=a.u[b]|0;a.b=d;return"(?:\\"+b+")";case 107:return a.b=1+a.b|0,a.b!==c&&60===b.charCodeAt(a.b)||E(a,"\\k is not followed by '\x3c' for named capturing group"),a.b=1+a.b|0,b=nb(a),d=a.ra,Xa().oa.call(d,
b)||E(a,"named capturing group \x3c"+b+"\x3e does not exit"),b=a.u[d[b]|0]|0,a.b=1+a.b|0,"(?:\\"+b+")";case 81:d=1+a.b|0;c=b.indexOf("\\E",d)|0;if(0>c)return a.b=b.length,ab(a,b.substring(d));a.b=2+c|0;return ab(a,b.substring(d,c));default:return cb(a,ob(a))}}
function ob(a){var b=a.j,c=bb(b,a.b);switch(c){case 48:return pb(a);case 120:return b=a.j,c=1+a.b|0,c!==b.length&&123===b.charCodeAt(c)?(c=1+c|0,b=b.indexOf("}",c)|0,0>b&&E(a,"Unclosed hexadecimal escape sequence"),c=qb(a,c,b,"hexadecimal"),a.b=1+b|0,a=c):(b=qb(a,c,2+c|0,"hexadecimal"),a.b=2+c|0,a=b),a;case 117:a:{b=a.j;var d=1+a.b|0;c=4+d|0;d=qb(a,d,c,"Unicode");a.b=c;var e=2+c|0,f=4+e|0;if(55296===(-1024&d)&&"\\u"===b.substring(c,e)&&(b=qb(a,e,f,"Unicode"),56320===(-1024&b))){a.b=f;a=(64+(1023&
d)|0)<<10|1023&b;break a}a=d}return a;case 78:E(a,"\\N is not supported");break;case 97:return a.b=1+a.b|0,7;case 116:return a.b=1+a.b|0,9;case 110:return a.b=1+a.b|0,10;case 102:return a.b=1+a.b|0,12;case 114:return a.b=1+a.b|0,13;case 101:return a.b=1+a.b|0,27;case 99:return a.b=1+a.b|0,a.b===b.length&&E(a,"Illegal control escape sequence"),b=bb(b,a.b),a.b=a.b+(65536<=b?2:1)|0,64^b;default:return(65<=c&&90>=c||97<=c&&122>=c)&&E(a,"Illegal/unsupported escape sequence"),a.b=a.b+(65536<=c?2:1)|0,c}}
function pb(a){var b=a.j,c=b.length,d=a.b,e=(1+d|0)<c?-48+b.charCodeAt(1+d|0)|0:-1;(0>e||7<e)&&E(a,"Illegal octal escape sequence");var f=(2+d|0)<c?-48+b.charCodeAt(2+d|0)|0:-1;if(0>f||7<f)return a.b=2+a.b|0,e;if(3<e)return a.b=3+a.b|0,(e<<3)+f|0;b=(3+d|0)<c?-48+b.charCodeAt(3+d|0)|0:-1;if(0>b||7<b)return a.b=3+a.b|0,(e<<3)+f|0;a.b=4+a.b|0;return((e<<6)+(f<<3)|0)+b|0}
function qb(a,b,c,d){var e=a.j,f=e.length;(b===c||c>f)&&E(a,"Illegal "+d+" escape sequence");for(f=b;f<c;){var g=e.charCodeAt(f);48<=g&&57>=g||65<=g&&70>=g||97<=g&&102>=g||E(a,"Illegal "+d+" escape sequence");f=1+f|0}6<(c-b|0)?b=1114112:(b=e.substring(b,c),b=parseInt(b,16)|0);1114111<b&&E(a,"Hexadecimal codepoint is too big");return b}
function jb(a,b){a.b=1+a.b|0;switch(b){case 100:case 68:a=F().xb;break;case 104:case 72:a=F().Ab;break;case 115:case 83:a=F().yb;break;case 118:case 86:a=F().Bb;break;case 119:case 87:a=F().zb;break;case 112:case 80:var c=a.j,d=a.b;if(d===c.length)c="?";else if(123===c.charCodeAt(d)){d=1+d|0;var e=c.indexOf("}",d)|0;0>e&&E(a,"Unclosed character family");a.b=e;c=c.substring(d,e)}else c=c.substring(d,1+d|0);d=F().Qa;Xa().oa.call(d,c)||mb(a,"Unicode character family");c=2!==(66&a.e)||"Lower"!==c&&"Upper"!==
c?c:"Alpha";c=F().Qa[c];a.b=1+a.b|0;a=c;break;default:throw new lb(new l(b));}97<=b?b=a:a.Ma?b=a.Oa:(b=a,b.Ma||(b.Oa=new G(1^b.Na,b.G),b.Ma=!0),b=b.Oa);return b}
var wb=function rb(a){var c=a.j,d=c.length;a.b=1+a.b|0;var e=a.b!==d?94===c.charCodeAt(a.b):!1;e&&(a.b=1+a.b|0);for(e=new sb(2===(66&a.e),e);a.b!==d;){var f=bb(c,a.b);a:{switch(f){case 93:return a.b=1+a.b|0,a=e,c=tb(a),""===a.qa?c:"(?:"+a.qa+c+")";case 38:a.b=1+a.b|0;if(a.b!==d&&38===c.charCodeAt(a.b)){a.b=1+a.b|0;f=e;var g=tb(f);f.qa+=f.wb?g+"|":"(?\x3d"+g+")";f.q="";f.g=""}else ub(a,38,d,c,e);break a;case 91:f=rb(a);e.q=""===e.q?f:e.q+"|"+f;break a;case 92:a.b=1+a.b|0;a.b===d&&E(a,"Illegal escape sequence");
g=c.charCodeAt(a.b);switch(g){case 100:case 68:case 104:case 72:case 115:case 83:case 118:case 86:case 119:case 87:case 112:case 80:f=e;g=jb(a,g);var k=g.Na;switch(k){case 0:f.g=f.g+("\\p{"+g.G)+"}";break;case 1:f.g=f.g+("\\P{"+g.G)+"}";break;case 2:f.g=""+f.g+g.G;break;case 3:g=kb(F(),g.G);f.q=""===f.q?g:f.q+"|"+g;break;default:throw new lb(k);}break;case 81:a.b=1+a.b|0;f=c.indexOf("\\E",a.b)|0;0>f&&E(a,"Unclosed character class");g=e;k=c;for(var m=f,y=a.b;y!==m;){var B=bb(k,y);vb(g,B);y=y+(65536<=
B?2:1)|0}a.b=2+f|0;break;default:ub(a,ob(a),d,c,e)}break a;case 32:case 9:case 10:case 11:case 12:case 13:if(0!==(4&a.e))a.b=1+a.b|0;else break;break a;case 35:if(0!==(4&a.e)){fb(a);break a}}a.b=a.b+(65536<=f?2:1)|0;ub(a,f,d,c,e)}}E(a,"Unclosed character class")};
function xb(a){var b=a.j,c=b.length,d=a.b;if((1+d|0)===c||63!==b.charCodeAt(1+d|0))return a.b=1+d|0,a.t=1+a.t|0,a.u.push(a.t),"("+yb(a,!0)+")";(2+d|0)===c&&E(a,"Unclosed group");var e=b.charCodeAt(2+d|0);if(58===e||61===e||33===e)return a.b=3+d|0,""+b.substring(d,3+d|0)+yb(a,!0)+")";if(60===e){(3+d|0)===c&&E(a,"Unclosed group");b=b.charCodeAt(3+d|0);if(65<=b&&90>=b||97<=b&&122>=b)return a.b=3+d|0,d=nb(a),b=a.ra,Xa().oa.call(b,d)&&E(a,"named capturing group \x3c"+d+"\x3e is already defined"),a.t=1+
a.t|0,a.u.push(a.t),a.ra[d]=-1+(a.u.length|0)|0,a.b=1+a.b|0,"("+yb(a,!0)+")";61!==b&&33!==b&&E(a,"Unknown look-behind group");mb(a,"Look-behind group")}else{if(62===e)return a.b=3+d|0,a.t=1+a.t|0,d=a.t,"(?:(?\x3d("+yb(a,!0)+"))\\"+d+")";E(a,"Embedded flag expression in the middle of a pattern is not supported")}}
function nb(a){for(var b=a.j,c=b.length,d=a.b;;){if(a.b!==c){var e=b.charCodeAt(a.b);e=65<=e&&90>=e||97<=e&&122>=e||48<=e&&57>=e}else e=!1;if(e)a.b=1+a.b|0;else break}a.b!==c&&62===b.charCodeAt(a.b)||E(a,"named capturing group is missing trailing '\x3e'");return b.substring(d,a.b)}
function ub(a,b,c,d,e){0!==(4&a.e)&&eb(a);a.b!==c&&45===d.charCodeAt(a.b)?(a.b=1+a.b|0,0!==(4&a.e)&&eb(a),a.b===c&&E(a,"Unclosed character class"),c=bb(d,a.b),91===c||93===c?(vb(e,b),vb(e,45)):(a.b=a.b+(65536<=c?2:1)|0,c=92===c?ob(a):c,c<b&&E(a,"Illegal character range"),a=zb(b)+"-"+zb(c),e.g=56320===(-1024&b)?a+e.g:e.g+a,e.vb&&(a=65<b?b:65,d=90>c?c:90,a<=d&&(d=32+d|0,e.g+=zb(32+a|0)+"-"+zb(d)),b=97<b?b:97,c=122>c?c:122,b<=c&&(c=-32+c|0,e.g+=zb(-32+b|0)+"-"+zb(c))))):vb(e,b)}
function Ab(a,b){this.j=a;this.e=b;this.Ra=!1;this.t=this.b=0;this.u=[0];this.ra={}}Ab.prototype=new v;Ab.prototype.constructor=Ab;function mb(a,b){E(a,b+" is not supported because it requires RegExp features of ECMAScript 2018.\nIf you only target environments with ES2018+, you can enable ES2018 features with\n  scalaJSLinkerConfig ~\x3d { _.withESFeatures(_.withESVersion(ESVersion.ES2018)) }\nor an equivalent configuration depending on your build tool.")}
function yb(a,b){for(var c=a.j,d=c.length,e="";a.b!==d;){var f=bb(c,a.b);a:{switch(f){case 41:return b||E(a,"Unmatched closing ')'"),a.b=1+a.b|0,e;case 124:a.Ra&&!b&&E(a,"\\G is not supported when there is an alternative at the top level");a.b=1+a.b|0;e+="|";break a;case 32:case 9:case 10:case 11:case 12:case 13:if(0!==(4&a.e))a.b=1+a.b|0;else break;break a;case 35:if(0!==(4&a.e))fb(a);else break;break a;case 63:case 42:case 43:case 123:E(a,"Dangling meta character '"+db(F(),f)+"'")}var g=a.t;switch(f){case 92:f=
ib(a);break;case 91:f=wb(a);break;case 40:f=xb(a);break;case 94:a.b=1+a.b|0;f="^";break;case 36:a.b=1+a.b|0;f="$";break;case 46:a.b=1+a.b|0;f=0!==(32&a.e)?"":0!==(1&a.e)?"\n":"\n\r\u0085\u2028\u2029";f=kb(F(),f);break;default:a.b=a.b+(65536<=f?2:1)|0,f=cb(a,f)}e=""+e+gb(a,g,f)}}b&&E(a,"Unclosed group");return e}function fb(a){for(var b=a.j,c=b.length;;){if(a.b!==c){var d=b.charCodeAt(a.b);d=!(10===d||13===d||133===d||8232===d||8233===d)}else d=!1;if(d)a.b=1+a.b|0;else break}}
Ab.prototype.$classData=C({Mc:0},"java.util.regex.PatternCompiler",{Mc:1,c:1});function Bb(a){try{return RegExp("",a),!0}catch(b){return!1}}
function Cb(){this.Db=this.Cb=null;this.Pa=!1;this.Qa=this.zb=this.Bb=this.yb=this.Ab=this.xb=null;Db=this;this.Cb=RegExp("^\\(\\?([idmsuxU]*)(?:-([idmsuxU]*))?\\)");this.Db=RegExp("(\\\\+)(\\d+)","g");this.Pa=Bb("us");Bb("d");this.xb=new G(2,"0-9");this.Ab=new G(2,"\t \u00a0\u1680\u180e\u2000-\u200a\u202f\u205f\u3000");this.yb=new G(2,"\t-\r ");this.Bb=new G(2,"\n-\r\u0085\u2028\u2029");this.zb=new G(2,"a-zA-Z_0-9");var a={};a.Lower=new G(2,"a-z");a.Upper=new G(2,"A-Z");a.ASCII=new G(2,"\x00-\u007f");
a.Alpha=new G(2,"A-Za-z");a.Digit=new G(2,"0-9");a.Alnum=new G(2,"0-9A-Za-z");a.Punct=new G(2,"!-/:-@[-`{-~");a.Graph=new G(2,"!-~");a.Print=new G(2," -~");a.Blank=new G(2,"\t ");a.Cntrl=new G(2,"\x00-\u001f\u007f");a.XDigit=new G(2,"0-9A-Fa-f");a.Space=new G(2,"\t-\r ");this.Qa=a}Cb.prototype=new v;Cb.prototype.constructor=Cb;
function Eb(a,b){switch(b){case 105:return 2;case 100:return 1;case 109:return 8;case 115:return 32;case 117:return 64;case 120:return 4;case 85:return 256;default:throw Fb("bad in-pattern flag");}}function kb(a,b){return""!==b?"[^"+b+"]":F().Pa?".":"[\\d\\D]"}function db(a,b){return String.fromCodePoint(b)}Cb.prototype.$classData=C({Nc:0},"java.util.regex.PatternCompiler$",{Nc:1,c:1});var Db;function F(){Db||(Db=new Cb);return Db}
function tb(a){if(a.wb){var b=kb(F(),a.g);return""===a.q?b:"(?:(?!"+a.q+")"+b+")"}return""===a.g?""===a.q?"[^\\d\\D]":"(?:"+a.q+")":""===a.q?"["+a.g+"]":"(?:"+a.q+"|["+a.g+"])"}function zb(a){var b=db(F(),a);return 93===a||92===a||45===a||94===a?"\\"+b:b}function sb(a,b){this.vb=a;this.wb=b;this.g=this.q=this.qa=""}sb.prototype=new v;sb.prototype.constructor=sb;
function vb(a,b){var c=zb(b);a.g=56320===(-1024&b)?""+c+a.g:""+a.g+c;a.vb&&(65<=b&&90>=b?a.g=""+a.g+db(F(),32+b|0):97<=b&&122>=b&&(a.g=""+a.g+db(F(),-32+b|0)))}sb.prototype.$classData=C({Oc:0},"java.util.regex.PatternCompiler$CharacterClassBuilder",{Oc:1,c:1});function G(a,b){this.Oa=null;this.Ma=!1;this.Na=a;this.G=b}G.prototype=new v;G.prototype.constructor=G;G.prototype.$classData=C({Pc:0},"java.util.regex.PatternCompiler$CompiledCharClass",{Pc:1,c:1});
function Gb(a){a.ia||(a.ja=StrictMath,a.ia=!0);return a.ja}function Hb(){this.ja=null;this.ia=!1}Hb.prototype=new v;Hb.prototype.constructor=Hb;Hb.prototype.$classData=C({Zb:0},"org.nlogo.tortoise.engine.MersenneMath$",{Zb:1,c:1});var Ib;function Jb(){Ib||(Ib=new Hb);return Ib}function p(a,b){this.i=a;this.l=b}p.prototype=new v;p.prototype.constructor=p;p.prototype.B=function(a){return a instanceof p?this.i===a.i&&this.l===a.l:!1};p.prototype.y=function(){return this.i^this.l};
p.prototype.r=function(){var a=H(),b=this.i,c=this.l;return c===b>>31?""+b:0>c?"-"+Kb(a,-b|0,0!==b?~c:-c|0):Kb(a,b,c)};p.prototype.$classData=C({cc:0},"org.scalajs.linker.runtime.RuntimeLong",{cc:1,c:1});function Kb(a,b,c){return 0===(-2097152&c)?""+(4294967296*c+ +(b>>>0)):Lb(a,b,c,1E9,0,2)}
function Lb(a,b,c,d,e,f){var g=(0!==e?Math.clz32(e)|0:32+(Math.clz32(d)|0)|0)-(0!==c?Math.clz32(c)|0:32+(Math.clz32(b)|0)|0)|0,k=g,m=0===(32&k)?d<<k:0,y=0===(32&k)?(d>>>1|0)>>>(31-k|0)|0|e<<k:d<<k;k=b;var B=c;for(b=c=0;0<=g&&0!==(-2097152&B);){var J=k,M=B,gf=m,Qd=y;if(M===Qd?(-2147483648^J)>=(-2147483648^gf):(-2147483648^M)>=(-2147483648^Qd))J=B,M=y,B=k-m|0,J=(-2147483648^B)>(-2147483648^k)?-1+(J-M|0)|0:J-M|0,k=B,B=J,32>g?c|=1<<g:b|=1<<g;g=-1+g|0;J=y>>>1|0;m=m>>>1|0|y<<31;y=J}g=B;if(g===e?(-2147483648^
k)>=(-2147483648^d):(-2147483648^g)>=(-2147483648^e))g=4294967296*B+ +(k>>>0),d=4294967296*e+ +(d>>>0),1!==f&&(y=g/d,e=y/4294967296|0,m=c,c=y=m+(y|0)|0,b=(-2147483648^y)<(-2147483648^m)?1+(b+e|0)|0:b+e|0),0!==f&&(d=g%d,k=d|0,B=d/4294967296|0);if(0===f)return a.k=b,c;if(1===f)return a.k=B,k;a=""+k;return""+(4294967296*b+ +(c>>>0))+"000000000".substring(a.length)+a}function Mb(){this.k=0}Mb.prototype=new v;Mb.prototype.constructor=Mb;
function Nb(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}function Ob(a,b){if(-0x7fffffffffffffff>b)return a.k=-2147483648,0;if(0x7fffffffffffffff<=b)return a.k=2147483647,-1;var c=b|0,d=b/4294967296|0;a.k=0>b&&0!==c?-1+d|0:d;return c}
function Pb(a,b,c,d,e){if(0===(d|e))throw new xa;if(c===b>>31){if(e===d>>31)return-1!==d?(c=wa(b,d),a.k=c>>31,c):a.k=0;if(-2147483648===b&&-2147483648===d&&0===e)return a.k=0;a.k=c;return b}if(0>c)var f=-b|0,g=0!==b?~c:-c|0;else f=b,g=c;0>e?(b=-d|0,d=0!==d?~e:-e|0):(b=d,d=e);0===(-2097152&g)?0===(-2097152&d)?(b=(4294967296*g+ +(f>>>0))%(4294967296*d+ +(b>>>0)),a.k=b/4294967296|0,b|=0):(a.k=g,b=f):0===d&&0===(b&(-1+b|0))?(a.k=0,b=f&(-1+b|0)):0===b&&0===(d&(-1+d|0))?(a.k=g&(-1+d|0),b=f):b=Lb(a,f,g,
b,d,1)|0;return 0>c?(c=a.k,a.k=0!==b?~c:-c|0,-b|0):b}Mb.prototype.$classData=C({dc:0},"org.scalajs.linker.runtime.RuntimeLong$",{dc:1,c:1});var Qb;function H(){Qb||(Qb=new Mb);return Qb}function Rb(){}Rb.prototype=new v;Rb.prototype.constructor=Rb;function Sb(){}Sb.prototype=Rb.prototype;function Tb(){this.fa=null;Ub=this;this.fa=new Vb}Tb.prototype=new v;Tb.prototype.constructor=Tb;Tb.prototype.$classData=C({Hd:0},"scala.collection.Iterator$",{Hd:1,c:1});var Ub;
function Wb(){Ub||(Ub=new Tb);return Ub}function Xb(){}Xb.prototype=new v;Xb.prototype.constructor=Xb;function Yb(){}Yb.prototype=Xb.prototype;function Zb(){}Zb.prototype=new v;Zb.prototype.constructor=Zb;function $b(){}$b.prototype=Zb.prototype;function ac(){}ac.prototype=new v;ac.prototype.constructor=ac;ac.prototype.$classData=C({fe:0},"scala.collection.immutable.StringOps$",{fe:1,c:1});var bc;
function cc(){dc=this;ec||(ec=new fc);gc||(gc=new hc);ic||(ic=new jc);kc||(kc=new lc);Wb();mc||(mc=new nc);oc();pc||(pc=new qc);rc||(rc=new sc)}cc.prototype=new v;cc.prototype.constructor=cc;cc.prototype.$classData=C({fd:0},"scala.package$",{fd:1,c:1});var dc;function tc(){uc=this;vc||(vc=new wc);xc||(xc=new yc);zc||(zc=new Ac);Bc||(Bc=new Cc);Dc||(Dc=new Ec)}tc.prototype=new v;tc.prototype.constructor=tc;tc.prototype.$classData=C({gd:0},"scala.reflect.ClassManifestFactory$",{gd:1,c:1});var uc;
function Fc(){}Fc.prototype=new v;Fc.prototype.constructor=Fc;Fc.prototype.$classData=C({hd:0},"scala.reflect.ManifestFactory$",{hd:1,c:1});var Gc;function Hc(){Ic=this;uc||(uc=new tc);Gc||(Gc=new Fc)}Hc.prototype=new v;Hc.prototype.constructor=Hc;Hc.prototype.$classData=C({nd:0},"scala.reflect.package$",{nd:1,c:1});var Ic;function Jc(){}Jc.prototype=new v;Jc.prototype.constructor=Jc;
function Kc(a,b,c){if(b===c)c=!0;else if(Lc(b))a:if(Lc(c))c=Mc(b,c);else{if(c instanceof l){if("number"===typeof b){c=+b===r(c);break a}if(b instanceof p){a=q(b);b=a.l;c=r(c);c=a.i===c&&b===c>>31;break a}}c=null===b?null===c:ta(b,c)}else c=b instanceof l?Nc(b,c):null===b?null===c:ta(b,c);return c}
function Mc(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(b instanceof p){var c=q(b);b=c.i;c=c.l;return a===Nb(H(),b,c)}return!1}if(a instanceof p){c=q(a);a=c.i;c=c.l;if(b instanceof p){b=q(b);var d=b.l;return a===b.i&&c===d}return"number"===typeof b?(b=+b,Nb(H(),a,c)===b):!1}return null===a?null===b:ta(a,b)}
function Nc(a,b){if(b instanceof l)return r(a)===r(b);if(Lc(b)){if("number"===typeof b)return+b===r(a);if(b instanceof p){b=q(b);var c=b.l;a=r(a);return b.i===a&&c===a>>31}return null===b?null===a:ta(b,a)}return null===a&&null===b}Jc.prototype.$classData=C({je:0},"scala.runtime.BoxesRunTime$",{je:1,c:1});var Oc;function Pc(){Oc||(Oc=new Jc);return Oc}function Qc(){}Qc.prototype=new v;Qc.prototype.constructor=Qc;
function Rc(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=ya(a);if(b===a)a=b;else{var c=H();b=Ob(c,a);c=c.k;a=Nb(H(),b,c)===a?b^c:Ra(Sa(),a)}return a}return b instanceof p?(a=q(b),b=new p(a.i,a.l),a=b.i,b=b.l,b===a>>31?a:a^b):ua(b)}Qc.prototype.$classData=C({ke:0},"scala.runtime.Statics$",{ke:1,c:1});var Sc;function Tc(){Sc||(Sc=new Qc);return Sc}function Uc(){new Vc}Uc.prototype=new v;Uc.prototype.constructor=Uc;Uc.prototype.$classData=C({pd:0},"scala.util.control.Breaks",{pd:1,c:1});
function Wc(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function Xc(){}Xc.prototype=new v;Xc.prototype.constructor=Xc;function Yc(){}Yc.prototype=Xc.prototype;function Zc(a,b){a=$c(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function $c(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}
function ad(a){0===(32&a.ma)<<24>>24&&0===(32&a.ma)<<24>>24&&(a.nb=new x(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.ma=(32|a.ma)<<24>>24);return a.nb}function bd(){this.nb=null;this.ma=0}bd.prototype=new v;bd.prototype.constructor=bd;
bd.prototype.$classData=C({lc:0},"java.lang.Character$",{lc:1,c:1,d:1});var cd;function dd(a){throw new ed('For input string: "'+a+'"');}function fd(){this.ob=this.pb=null;this.I=0}fd.prototype=new v;fd.prototype.constructor=fd;fd.prototype.$classData=C({oc:0},"java.lang.Double$",{oc:1,c:1,d:1});var gd;function hd(a){throw new ed('For input string: "'+a+'"');}function id(){}id.prototype=new v;id.prototype.constructor=id;
function jd(a){var b=null===a?0:a.length;0===b&&hd(a);var c=a.charCodeAt(0),d=45===c,e=d?2147483648:2147483647;c=d||43===c?1:0;c>=a.length&&hd(a);for(var f=0;c!==b;){cd||(cd=new bd);var g=cd;var k=a.charCodeAt(c);if(256>k)g=48<=k&&57>=k?-48+k|0:65<=k&&90>=k?-55+k|0:97<=k&&122>=k?-87+k|0:-1;else if(65313<=k&&65338>=k)g=-65303+k|0;else if(65345<=k&&65370>=k)g=-65335+k|0;else{Za||(Za=new Ya);a:{var m=ad(g);for(var y=0,B=m.a.length;;){if(y===B){m=-1-y|0;break a}var J=(y+B|0)>>>1|0,M=m.a[J];M=k===M?0:
k<M?-1:1;if(0>M)B=J;else{if(0===M){m=J;break a}y=1+J|0}}}m=0>m?-2-m|0:m;0>m?g=-1:(g=k-ad(g).a[m]|0,g=9<g?-1:g)}g=10>g?g:-1;f=10*f+g;(-1===g||f>e)&&hd(a);c=1+c|0}return d?-f|0:f|0}id.prototype.$classData=C({uc:0},"java.lang.Integer$",{uc:1,c:1,d:1});var kd;function ld(){kd||(kd=new id)}function Lc(a){return"number"===typeof a||a instanceof p}function I(a,b){a.sb=b;a.Ha()}
class md extends Error{constructor(){super();this.sb=null}Ia(){return this.sb}Ha(){"[object Error]"!==Object.prototype.toString.call(this)&&(void 0===Error.captureStackTrace?Error():Error.captureStackTrace(this));return this}r(){var a=sa(this),b=this.Ia();return null===b?a:a+": "+b}y(){return t.prototype.y.call(this)}B(a){return t.prototype.B.call(this,a)}get message(){var a=this.Ia();return null===a?"":a}get name(){return sa(this)}toString(){return this.r()}}function nd(){}nd.prototype=new v;
nd.prototype.constructor=nd;function od(){}od.prototype=nd.prototype;function pd(){var a=4294967296*+Math.random();return ya(+Math.floor(a)-2147483648)}function qd(){}qd.prototype=new v;qd.prototype.constructor=qd;qd.prototype.$classData=C({Gc:0},"java.util.Random$",{Gc:1,c:1,d:1});var rd;function sd(a){if(null===a.La)throw new td;return a.La}function ud(a,b){this.Jc=a;this.Ic=b;this.Kc=0;this.tb=this.Ic;this.ub=0;this.La=null}ud.prototype=new v;ud.prototype.constructor=ud;
function vd(a){var b=a.Jc;var c=a.tb;var d=b.Sa;d.lastIndex=a.ub;c=d.exec(c);b=b.Sa.lastIndex|0;a.ub=null!==c?b===(c.index|0)?1+b|0:b:1+a.tb.length|0;a.La=c;return null!==c}function wd(a){return(sd(a).index|0)+a.Kc|0}function xd(a){var b=wd(a);a=sd(a)[0];return b+a.length|0}ud.prototype.$classData=C({Hc:0},"java.util.regex.Matcher",{Hc:1,c:1,pe:1});function yd(a,b,c,d,e){this.Sa=null;this.Uc=a;this.Vc=d;this.Wc=e;this.Sa=new RegExp(c,this.Vc+(this.Wc?"gy":"g"));new RegExp("^(?:"+c+")$",d)}
yd.prototype=new v;yd.prototype.constructor=yd;yd.prototype.r=function(){return this.Uc};yd.prototype.$classData=C({Lc:0},"java.util.regex.Pattern",{Lc:1,c:1,d:1});function zd(a){if(null===a)throw null;}zd.prototype=new v;zd.prototype.constructor=zd;zd.prototype.$classData=C({Sd:0},"scala.collection.generic.GenMapFactory$MapCanBuildFrom",{Sd:1,c:1,bb:1});function Ad(){}Ad.prototype=new $b;Ad.prototype.constructor=Ad;function Bd(){}Bd.prototype=Ad.prototype;function Cd(a){if(null===a)throw null;}
Cd.prototype=new v;Cd.prototype.constructor=Cd;Cd.prototype.$classData=C({Td:0},"scala.collection.generic.GenSetFactory$$anon$1",{Td:1,c:1,bb:1});function Dd(a){new Ed(a)}function Fd(){}Fd.prototype=new $b;Fd.prototype.constructor=Fd;function Gd(){}Gd.prototype=Fd.prototype;function Hd(){}Hd.prototype=new v;Hd.prototype.constructor=Hd;function Id(){}Id.prototype=Hd.prototype;function Jd(){}Jd.prototype=new Yb;Jd.prototype.constructor=Jd;function Kd(){}Kd.prototype=Jd.prototype;function Ld(){}
Ld.prototype=new v;Ld.prototype.constructor=Ld;function Md(){}Md.prototype=Ld.prototype;Ld.prototype.r=function(){return"\x3cfunction1\x3e"};function Nd(){this.Ib=this.Va=0;Od=this;this.Va=u("Seq");this.Ib=u("Map");u("Set");Pd||(Pd=new Rd);var a=Pd;var b=this.Ib;if(a.m()){var c=Zc(b,0);c=Zc(c,0);c=$c(c,1);Wc(c^0)}else c=new Sd(this),a.M(c),a=Zc(b,c.Wa),a=Zc(a,c.Xa),a=$c(a,c.Ya),Wc(a^c.Za)}Nd.prototype=new Yc;Nd.prototype.constructor=Nd;
function Td(a){var b=Ud();if(a instanceof Vd){for(b=b.Va;!a.m();)Wd();a=Wc(b^0)}else{var c=b.Va;a.m()?a=Wc(c^0):(b=new Xd(b,c),a.M(b),a=Wc(b.ya^b.za))}return a}Nd.prototype.$classData=C({sd:0},"scala.util.hashing.MurmurHash3$",{sd:1,Be:1,c:1});var Od;function Ud(){Od||(Od=new Nd);return Od}function Na(a){this.ba=a}Na.prototype=new v;Na.prototype.constructor=Na;Na.prototype.r=function(){return(this.ba.isInterface?"interface ":this.ba.isPrimitive?"":"class ")+this.ba.name};
Na.prototype.$classData=C({mc:0},"java.lang.Class",{mc:1,c:1,d:1,F:1});class Yd extends md{}class Zd extends md{}
function $d(){this.jb=this.ib=this.eb=this.kb=this.gb=this.fb=this.hb=0;this.db=null;this.h=0;ae=this;this.hb=624;this.h=(1|this.h)<<24>>24;this.fb=397;this.h=(2|this.h)<<24>>24;this.gb=-1727483681;this.h=(4|this.h)<<24>>24;this.kb=-2147483648;this.h=(8|this.h)<<24>>24;this.eb=2147483647;this.h=(16|this.h)<<24>>24;this.ib=-1658038656;this.h=(32|this.h)<<24>>24;this.jb=-272236544;this.h=(64|this.h)<<24>>24;this.db="0";this.h=(128|this.h)<<24>>24}$d.prototype=new v;$d.prototype.constructor=$d;
function K(){var a=L();if(0===(1&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 142");return a.hb}function O(){var a=L();if(0===(2&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 143");return a.fb}
function P(){var a=L();if(0===(8&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 145");return a.kb}function Q(){var a=L();if(0===(16&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 146");return a.eb}
function R(){var a=L();if(0===(32&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 147");return a.ib}function S(){var a=L();if(0===(64&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 148");return a.jb}
function be(){var a=L();if(0===(128&a.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 149");return a.db}$d.prototype.$classData=C({ac:0},"org.nlogo.tortoise.engine.MersenneTwisterFast$",{ac:1,c:1,o:1,d:1});var ae;function L(){ae||(ae=new $d);return ae}function ce(){de=this;dc||(dc=new cc);mc||(mc=new nc);ee||(ee=new fe);ge||(ge=new he);Ic||(Ic=new Hc);Ic||(Ic=new Hc)}ce.prototype=new Sb;ce.prototype.constructor=ce;
ce.prototype.$classData=C({$c:0},"scala.Predef$",{$c:1,se:1,c:1,qe:1});var de;function ie(a,b,c){this.ab=b;this.Rd=c;this.Ub=!0}ie.prototype=new Md;ie.prototype.constructor=ie;ie.prototype.W=function(a){if(this.Ub){var b=this.ab.A;b.n+=""+a;this.Ub=!1}else je(this.ab,this.Rd),b=this.ab.A,b.n+=""+a};ie.prototype.H=function(a){this.W(a)};ie.prototype.$classData=C({Qd:0},"scala.collection.TraversableOnce$appender$1",{Qd:1,Xb:1,c:1,ha:1});function ke(){}ke.prototype=new Gd;ke.prototype.constructor=ke;
function le(){}le.prototype=ke.prototype;function Ed(a){if(null===a)throw null;if(null===a)throw null;}Ed.prototype=new Id;Ed.prototype.constructor=Ed;Ed.prototype.$classData=C({Ud:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{Ud:1,Vd:1,c:1,bb:1});function me(){}me.prototype=new Kd;me.prototype.constructor=me;function ne(){}ne.prototype=me.prototype;function oe(){if(null===oc())throw null;}oe.prototype=new Id;oe.prototype.constructor=oe;
oe.prototype.$classData=C({ce:0},"scala.collection.immutable.Stream$StreamCanBuildFrom",{ce:1,Vd:1,c:1,bb:1});function pe(){this.rd=!1}pe.prototype=new v;pe.prototype.constructor=pe;pe.prototype.$classData=C({qd:0},"scala.util.control.NoStackTrace$",{qd:1,c:1,o:1,d:1});var qe;function Sd(){this.Za=this.Xa=this.Wa=0;this.Ya=1}Sd.prototype=new Md;Sd.prototype.constructor=Sd;
Sd.prototype.W=function(a){a=Rc(Tc(),a);this.Wa=this.Wa+a|0;this.Xa^=a;0!==a&&(this.Ya=Math.imul(this.Ya,a));this.Za=1+this.Za|0};Sd.prototype.H=function(a){this.W(a)};Sd.prototype.$classData=C({td:0},"scala.util.hashing.MurmurHash3$hasher$1",{td:1,Xb:1,c:1,ha:1});function Xd(a,b){this.ya=this.za=0;if(null===a)throw null;this.za=0;this.ya=b}Xd.prototype=new Md;Xd.prototype.constructor=Xd;Xd.prototype.W=function(a){this.ya=Zc(this.ya,Rc(Tc(),a));this.za=1+this.za|0};Xd.prototype.H=function(a){this.W(a)};
Xd.prototype.$classData=C({ud:0},"scala.util.hashing.MurmurHash3$hasher$2",{ud:1,Xb:1,c:1,ha:1});class lb extends Yd{constructor(a){super();I(this,""+a)}}lb.prototype.$classData=C({hc:0},"java.lang.AssertionError",{hc:1,me:1,s:1,c:1,d:1});var oa=C({ic:0},"java.lang.Boolean",{ic:1,c:1,d:1,D:1,F:1},a=>"boolean"===typeof a),ra=C({kc:0},"java.lang.Character",{kc:1,c:1,d:1,D:1,F:1},a=>a instanceof l);class T extends Zd{}T.prototype.$classData=C({z:0},"java.lang.RuntimeException",{z:1,E:1,s:1,c:1,d:1});
function re(){this.n=null}re.prototype=new v;re.prototype.constructor=re;re.prototype.r=function(){return this.n};re.prototype.v=function(){return this.n.length};re.prototype.$classData=C({zc:0},"java.lang.StringBuilder",{zc:1,c:1,mb:1,le:1,d:1});function se(){}se.prototype=new v;se.prototype.constructor=se;function te(){}te.prototype=se.prototype;se.prototype.m=function(){return!this.C()};se.prototype.M=function(a){for(;this.C();)a.H(this.J())};se.prototype.r=function(){return"\x3citerator\x3e"};
function ue(){}ue.prototype=new Bd;ue.prototype.constructor=ue;function ve(){}ve.prototype=ue.prototype;function fe(){ee=this;new zd(this)}fe.prototype=new ne;fe.prototype.constructor=fe;fe.prototype.$classData=C({Zd:0},"scala.collection.immutable.Map$",{Zd:1,Le:1,Ne:1,Ie:1,c:1});var ee;function sc(){rc=this;we||(we=new xe)}sc.prototype=new v;sc.prototype.constructor=sc;sc.prototype.$classData=C({dd:0},"scala.math.Ordering$",{dd:1,c:1,ve:1,o:1,d:1});var rc;
class xa extends T{constructor(){super();I(this,"/ by zero")}}xa.prototype.$classData=C({gc:0},"java.lang.ArithmeticException",{gc:1,z:1,E:1,s:1,c:1,d:1});var ia=C({jc:0},"java.lang.Byte",{jc:1,da:1,c:1,d:1,D:1,F:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);function Fb(a){var b=new ye;I(b,a);return b}class ye extends T{}ye.prototype.$classData=C({Ka:0},"java.lang.IllegalArgumentException",{Ka:1,z:1,E:1,s:1,c:1,d:1});class td extends T{constructor(){super();I(this,"No match available")}}
td.prototype.$classData=C({rc:0},"java.lang.IllegalStateException",{rc:1,z:1,E:1,s:1,c:1,d:1});class ze extends T{constructor(a){super();I(this,a)}}ze.prototype.$classData=C({sc:0},"java.lang.IndexOutOfBoundsException",{sc:1,z:1,E:1,s:1,c:1,d:1});class Ae extends T{constructor(){super();I(this,null)}}Ae.prototype.$classData=C({wc:0},"java.lang.NegativeArraySizeException",{wc:1,z:1,E:1,s:1,c:1,d:1});
var ja=C({yc:0},"java.lang.Short",{yc:1,da:1,c:1,d:1,D:1,F:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);class Be extends T{constructor(){super();I(this,"tail of empty list")}}Be.prototype.$classData=C({Bc:0},"java.lang.UnsupportedOperationException",{Bc:1,z:1,E:1,s:1,c:1,d:1});class Ce extends T{constructor(a){super();I(this,a)}}Ce.prototype.$classData=C({Fc:0},"java.util.NoSuchElementException",{Fc:1,z:1,E:1,s:1,c:1,d:1});
function U(a){if(0===(1&a.f)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 160");return a.la}function V(a){if(0===(2&a.f)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 161");return a.Fa}function W(a,b){a.Fa=b;a.f=(2|a.f)<<24>>24}
function X(a){if(0===(4&a.f)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 162");return a.ka}function De(a){if(0===(8&a.f)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 163");return a.Ea}function Ee(a,b){a.Ea=b;a.f=(8|a.f)<<24>>24}
function Fe(a){if(0===(16&a.f)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 164");return a.Da}function Ge(a,b){a.Da=b;a.f=(16|a.f)<<24>>24}
function Y(a){this.la=null;this.Fa=0;this.ka=null;this.Ea=0;this.Da=!1;this.f=0;this.bc=a;rd||(rd=new qd);var b=pd(),c=pd();He(this,new p(c,b));this.la=null;this.f=(1|this.f)<<24>>24;this.Fa=0;this.f=(2|this.f)<<24>>24;this.ka=null;this.f=(4|this.f)<<24>>24;this.Ea=0;this.f=(8|this.f)<<24>>24;this.Da=!1;this.f=(16|this.f)<<24>>24;He(this,a)}Y.prototype=new od;Y.prototype.constructor=Y;
function He(a,b){Ge(a,!1);Ee(a,0);var c=new x(K());a.la=c;a.f=(1|a.f)<<24>>24;c=new x(2);a.ka=c;a.f=(4|a.f)<<24>>24;X(a).a[0]=0;c=X(a).a;var d=L();if(0===(4&d.h)<<24>>24)throw new N("Uninitialized field: /home/anderiux/data/NetLogo/Tortoise/engine/src/main/scala/MersenneTwisterFast.scala: 144");c[1]=d.gb;U(a).a[0]=b.i;for(W(a,1);V(a)<K();)U(a).a[V(a)]=Math.imul(1812433253,U(a).a[-1+V(a)|0]^(U(a).a[-1+V(a)|0]>>>30|0))+V(a)|0,b=U(a),c=V(a),b.a[c]=b.a[c],W(a,1+V(a)|0)}
Y.prototype.nextInt=function(...a){switch(a.length|0){case 0:if(V(this)>=K()){for(var b=0,c=U(this),d=X(this);b<(K()-O()|0);)a=c.a[b]&P()|c.a[1+b|0]&Q(),c.a[b]=c.a[b+O()|0]^(a>>>1|0)^d.a[1&a],b=1+b|0;for(;b<(-1+K()|0);)a=c.a[b]&P()|c.a[1+b|0]&Q(),c.a[b]=c.a[b+(O()-K()|0)|0]^(a>>>1|0)^d.a[1&a],b=1+b|0;a=c.a[-1+K()|0]&P()|c.a[0]&Q();c.a[-1+K()|0]=c.a[-1+O()|0]^(a>>>1|0)^d.a[1&a];W(this,0)}a=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];a^=a>>>11|0;a^=a<<7&R();a^=a<<15&S();return a^(a>>>18|0);case 1:a=
a[0]|0;if(0>=a)throw Fb("n must be positive");if((a&(-a|0))===a){if(V(this)>=K()){b=0;d=U(this);for(var e=X(this);b<(K()-O()|0);)c=d.a[b]&P()|d.a[1+b|0]&Q(),d.a[b]=d.a[b+O()|0]^(c>>>1|0)^e.a[1&c],b=1+b|0;for(;b<(-1+K()|0);)c=d.a[b]&P()|d.a[1+b|0]&Q(),d.a[b]=d.a[b+(O()-K()|0)|0]^(c>>>1|0)^e.a[1&c],b=1+b|0;c=d.a[-1+K()|0]&P()|d.a[0]&Q();d.a[-1+K()|0]=d.a[-1+O()|0]^(c>>>1|0)^e.a[1&c];W(this,0)}c=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];c^=c>>>11|0;c^=c<<7&R();c^=c<<15&S();b=a>>31;c=(c^(c>>>18|0))>>>
1|0;d=c>>31;var f=65535&a;e=a>>>16|0;var g=65535&c,k=c>>>16|0,m=Math.imul(f,g);g=Math.imul(e,g);var y=Math.imul(f,k);f=m+((g+y|0)<<16)|0;m=(m>>>16|0)+y|0;a=(((Math.imul(a,d)+Math.imul(b,c)|0)+Math.imul(e,k)|0)+(m>>>16|0)|0)+(((65535&m)+g|0)>>>16|0)|0;a=f>>>31|0|a<<1}else{for(;;){if(V(this)>=K()){c=0;d=U(this);for(e=X(this);c<(K()-O()|0);)b=d.a[c]&P()|d.a[1+c|0]&Q(),d.a[c]=d.a[c+O()|0]^(b>>>1|0)^e.a[1&b],c=1+c|0;for(;c<(-1+K()|0);)b=d.a[c]&P()|d.a[1+c|0]&Q(),d.a[c]=d.a[c+(O()-K()|0)|0]^(b>>>1|0)^e.a[1&
b],c=1+c|0;b=d.a[-1+K()|0]&P()|d.a[0]&Q();d.a[-1+K()|0]=d.a[-1+O()|0]^(b>>>1|0)^e.a[1&b];W(this,0)}b=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];b^=b>>>11|0;b^=b<<7&R();b^=b<<15&S();b^=b>>>18|0;b=b>>>1|0;c=wa(b,a);if(!(0>((b-c|0)+(-1+a|0)|0)))break}a=c}return a;default:throw"No matching overload";}};
Y.prototype.nextGaussian=function(){if(Fe(this)){Ge(this,!1);var a=De(this)}else{for(var b,c;;){if(V(this)>=K()){a=0;var d=U(this);for(c=X(this);a<(K()-O()|0);)b=d.a[a]&P()|d.a[1+a|0]&Q(),d.a[a]=d.a[a+O()|0]^(b>>>1|0)^c.a[1&b],a=1+a|0;for(;a<(-1+K()|0);)b=d.a[a]&P()|d.a[1+a|0]&Q(),d.a[a]=d.a[a+(O()-K()|0)|0]^(b>>>1|0)^c.a[1&b],a=1+a|0;b=d.a[-1+K()|0]&P()|d.a[0]&Q();d.a[-1+K()|0]=d.a[-1+O()|0]^(b>>>1|0)^c.a[1&b];W(this,0)}b=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];b^=b>>>11|0;b^=b<<7&R();b^=b<<
15&S();b^=b>>>18|0;if(V(this)>=K()){a=0;d=U(this);for(var e=X(this);a<(K()-O()|0);)c=d.a[a]&P()|d.a[1+a|0]&Q(),d.a[a]=d.a[a+O()|0]^(c>>>1|0)^e.a[1&c],a=1+a|0;for(;a<(-1+K()|0);)c=d.a[a]&P()|d.a[1+a|0]&Q(),d.a[a]=d.a[a+(O()-K()|0)|0]^(c>>>1|0)^e.a[1&c],a=1+a|0;c=d.a[-1+K()|0]&P()|d.a[0]&Q();d.a[-1+K()|0]=d.a[-1+O()|0]^(c>>>1|0)^e.a[1&c];W(this,0)}c=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];c^=c>>>11|0;c^=c<<7&R();c^=c<<15&S();c^=c>>>18|0;if(V(this)>=K()){d=0;e=U(this);for(var f=X(this);d<(K()-O()|
0);)a=e.a[d]&P()|e.a[1+d|0]&Q(),e.a[d]=e.a[d+O()|0]^(a>>>1|0)^f.a[1&a],d=1+d|0;for(;d<(-1+K()|0);)a=e.a[d]&P()|e.a[1+d|0]&Q(),e.a[d]=e.a[d+(O()-K()|0)|0]^(a>>>1|0)^f.a[1&a],d=1+d|0;a=e.a[-1+K()|0]&P()|e.a[0]&Q();e.a[-1+K()|0]=e.a[-1+O()|0]^(a>>>1|0)^f.a[1&a];W(this,0)}a=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];a^=a>>>11|0;a^=a<<7&R();a^=a<<15&S();a^=a>>>18|0;if(V(this)>=K()){f=U(this);var g=X(this);for(e=0;e<(K()-O()|0);)d=f.a[e]&P()|f.a[1+e|0]&Q(),f.a[e]=f.a[e+O()|0]^(d>>>1|0)^g.a[1&d],e=1+e|
0;for(;e<(-1+K()|0);)d=f.a[e]&P()|f.a[1+e|0]&Q(),f.a[e]=f.a[e+(O()-K()|0)|0]^(d>>>1|0)^g.a[1&d],e=1+e|0;d=f.a[-1+K()|0]&P()|f.a[0]&Q();f.a[-1+K()|0]=f.a[-1+O()|0]^(d>>>1|0)^g.a[1&d];W(this,0)}d=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];d^=d>>>11|0;d^=d<<7&R();d^=d<<15&S();d^=d>>>18|0;e=b>>>6|0;b=e<<27;e=e>>>5|0|e>>31<<27;f=c>>>5|0;c=f>>31;f=b+f|0;b=(-2147483648^f)<(-2147483648^b)?1+(e+c|0)|0:e+c|0;b=2*(Nb(H(),f,b)/9007199254740992)-1;c=a>>>6|0;a=c<<27;c=c>>>5|0|c>>31<<27;e=d>>>5|0;d=e>>31;e=a+e|
0;a=(-2147483648^e)<(-2147483648^a)?1+(c+d|0)|0:c+d|0;a=2*(Nb(H(),e,a)/9007199254740992)-1;c=b*b+a*a;if(!(1<=c||0===c))break}d=Jb();e=Jb();f=c;c=-2*+(e.ia?e.ja:Gb(e)).log(f)/c;d=+(d.ia?d.ja:Gb(d)).sqrt(c);Ee(this,a*d);Ge(this,!0);a=b*d}return a};
Y.prototype.nextDouble=function(){if(V(this)>=K()){var a=0;for(var b=U(this),c=X(this);a<(K()-O()|0);){var d=b.a[a]&P()|b.a[1+a|0]&Q();b.a[a]=b.a[a+O()|0]^(d>>>1|0)^c.a[1&d];a=1+a|0}for(;a<(-1+K()|0);)d=b.a[a]&P()|b.a[1+a|0]&Q(),b.a[a]=b.a[a+(O()-K()|0)|0]^(d>>>1|0)^c.a[1&d],a=1+a|0;d=b.a[-1+K()|0]&P()|b.a[0]&Q();b.a[-1+K()|0]=b.a[-1+O()|0]^(d>>>1|0)^c.a[1&d];W(this,0)}d=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];d^=d>>>11|0;d^=d<<7&R();d^=d<<15&S();d^=d>>>18|0;if(V(this)>=K()){b=0;c=U(this);for(var e=
X(this);b<(K()-O()|0);)a=c.a[b]&P()|c.a[1+b|0]&Q(),c.a[b]=c.a[b+O()|0]^(a>>>1|0)^e.a[1&a],b=1+b|0;for(;b<(-1+K()|0);)a=c.a[b]&P()|c.a[1+b|0]&Q(),c.a[b]=c.a[b+(O()-K()|0)|0]^(a>>>1|0)^e.a[1&a],b=1+b|0;a=c.a[-1+K()|0]&P()|c.a[0]&Q();c.a[-1+K()|0]=c.a[-1+O()|0]^(a>>>1|0)^e.a[1&a];W(this,0)}a=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];a^=a>>>11|0;a^=a<<7&R();a^=a<<15&S();b=d>>>6|0;d=b<<27;b=b>>>5|0|b>>31<<27;c=(a^(a>>>18|0))>>>5|0;a=c>>31;c=d+c|0;d=(-2147483648^c)<(-2147483648^d)?1+(b+a|0)|0:b+a|0;return Nb(H(),
c,d)/9007199254740992};
Y.prototype.nextLong=function(a){var b=+a;a=H();b=Ob(a,b);a=new p(b,a.k);b=a.l;if(0===b?0===a.i:0>b)throw Fb("n must be positive");for(var c,d,e;;){if(V(this)>=K()){e=0;c=U(this);for(d=X(this);e<(K()-O()|0);)b=c.a[e]&P()|c.a[1+e|0]&Q(),c.a[e]=c.a[e+O()|0]^(b>>>1|0)^d.a[1&b],e=1+e|0;for(;e<(-1+K()|0);)b=c.a[e]&P()|c.a[1+e|0]&Q(),c.a[e]=c.a[e+(O()-K()|0)|0]^(b>>>1|0)^d.a[1&b],e=1+e|0;b=c.a[-1+K()|0]&P()|c.a[0]&Q();c.a[-1+K()|0]=c.a[-1+O()|0]^(b>>>1|0)^d.a[1&b];W(this,0)}b=U(this).a[W(this,1+V(this)|
0),-1+V(this)|0];b^=b>>>11|0;b^=b<<7&R();b^=b<<15&S();b^=b>>>18|0;if(V(this)>=K()){c=0;d=U(this);for(var f=X(this);c<(K()-O()|0);)e=d.a[c]&P()|d.a[1+c|0]&Q(),d.a[c]=d.a[c+O()|0]^(e>>>1|0)^f.a[1&e],c=1+c|0;for(;c<(-1+K()|0);)e=d.a[c]&P()|d.a[1+c|0]&Q(),d.a[c]=d.a[c+(O()-K()|0)|0]^(e>>>1|0)^f.a[1&e],c=1+c|0;e=d.a[-1+K()|0]&P()|d.a[0]&Q();d.a[-1+K()|0]=d.a[-1+O()|0]^(e>>>1|0)^f.a[1&e];W(this,0)}e=U(this).a[W(this,1+V(this)|0),-1+V(this)|0];e^=e>>>11|0;e^=e<<7&R();e^=e<<15&S();e^=e>>>18|0;c=b+(e>>31)|
0;b=c>>>1|0;c=e>>>1|0|c<<31;d=b;e=c;f=d;b=H();e=Pb(b,e,f,a.i,a.l);f=b.k;b=e;e=f;f=c;var g=e;c=f-b|0;d=(-2147483648^c)>(-2147483648^f)?-1+(d-g|0)|0:d-g|0;g=a.l;f=-1+a.i|0;g=-1!==f?g:-1+g|0;if(!(0>((-2147483648^(c+f|0))<(-2147483648^c)?1+(d+g|0)|0:d+g|0)))break}a=new p(b,e);return Nb(H(),a.i,a.l)};Y.prototype.setSeed=function(a){a|=0;He(this,new p(a,a>>31))};
Y.prototype.load=function(a){F();var b=new Ab("\\s",0);0!==(256&b.e)&&(b.e|=64);var c=0!==(16&b.e);if(!c){var d=F().Cb.exec(b.j);if(null!==d){var e=d[1];if(void 0!==e)for(var f=e.length,g=0;g<f;){var k=g;b.e|=Eb(F(),e.charCodeAt(k));g=1+g|0}0!==(256&b.e)&&(b.e|=64);e=d[2];if(void 0!==e)for(f=e.length,g=0;g<f;)k=g,b.e&=~Eb(F(),e.charCodeAt(k)),g=1+g|0;b.b=b.b+d[0].length|0}}0!==(128&b.e)&&E(b,"CANON_EQ is not supported");0!==(8&b.e)&&mb(b,"MULTILINE");0!==(256&b.e)&&mb(b,"UNICODE_CHARACTER_CLASS");
c?c=ab(b,b.j):("\\G"===b.j.substring(b.b,2+b.b|0)&&(b.Ra=!0,b.b=2+b.b|0),c=yb(b,!1));d=F().Pa?"us":"u";b=new yd(b.j,b.e,c,66===(66&b.e)?d+"i":d,b.Ra,-1+(b.u.length|0)|0,b.u,b.ra);if(""===a)a=new (Ma(fa).$)([""]);else{c=new ud(b,a);b=[];for(d=0;2147483646>(b.length|0)&&vd(c);)0!==xd(c)&&(e=wd(c),b.push(a.substring(d,e))),d=xd(c);b.push(a.substring(d));for(c=b.length|0;;)if(0!==c?(a=b[-1+c|0],a=null!==a&&ta(a,"")):a=!1,a)c=-1+c|0;else break;a=new (Ma(fa).$)(c);for(d=0;d<c;)e=d,a.a[e]=b[e],d=1+d|0}b=
a.a[0];if(b!==be())throw a=new T,b='identifier mismatch: expected "'+be()+'", got "'+b+'"',I(a,b),a;b=X(this);c=(new Z(a.a[1])).w;ld();b.a[0]=jd(c);b=X(this);c=(new Z(a.a[2])).w;ld();b.a[1]=jd(c);b=(new Z(a.a[3])).w;ld();W(this,jd(b));d=(new Z(a.a[4])).w;gd||(gd=new fd);b=gd;0===(1&b.I)<<24>>24&&0===(1&b.I)<<24>>24&&(b.pb=RegExp("^[\\x00-\\x20]*([+-]?(?:NaN|Infinity|(?:\\d+\\.?\\d*|\\.\\d+)(?:[eE][+-]?\\d+)?)[fFdD]?)[\\x00-\\x20]*$"),b.I=(1|b.I)<<24>>24);c=b.pb.exec(d);if(null!==c)b=+parseFloat(c[1]);
else{0===(2&b.I)<<24>>24&&0===(2&b.I)<<24>>24&&(b.ob=RegExp("^[\\x00-\\x20]*([+-]?)0[xX]([0-9A-Fa-f]*)\\.?([0-9A-Fa-f]*)[pP]([+-]?\\d+)[fFdD]?[\\x00-\\x20]*$"),b.I=(2|b.I)<<24>>24);c=b.ob.exec(d);null===c&&dd(d);b=c[1];f=c[2];e=c[3];c=c[4];""===f&&""===e&&dd(d);f=""+f+e;d=-(e.length<<2)|0;for(e=0;;)if(e!==f.length&&48===f.charCodeAt(e))e=1+e|0;else break;e=f.substring(e);if(""===e)c=0;else{g=e.length;if(f=15<g){k=!1;for(var m=15;!k&&m!==g;)48!==e.charCodeAt(m)&&(k=!0),m=1+m|0;g=k?"1":"0";g=e.substring(0,
15)+g}else g=e;e=d+(f?(e.length-16|0)<<2:0)|0;d=+parseInt(g,16);c=+parseInt(c,10);e=ya(c)+e|0;f=e/3|0;c=+Math.pow(2,f);e=+Math.pow(2,e-(f<<1)|0);c=d*c*c*e}b="-"===b?-c:c}Ee(this,b);b=a.a[5];if("true"===b)Ge(this,!0);else if("false"===b)Ge(this,!1);else throw a=new T,I(a,'expected true or false, got "'+b+'"'),a;for(b=0;b<K();)c=U(this),d=b,e=(new Z(a.a[6+b|0])).w,ld(),c.a[d]=jd(e),b=1+b|0;de||(de=new ce);if(!(a.a.length<=(6+b|0)))throw new lb("assertion failed");};
Y.prototype.save=function(){var a=De(this)===ya(De(this))?De(this)+".0":De(this),b=new Ie;a=be()+" "+X(this).a[0]+" "+X(this).a[1]+" "+V(this)+" "+a+" "+Fe(this);Je(b,a);for(a=0;a<K();){je(b," ");var c=U(this).a[a];je(b,""+c);a=1+a|0}return b.A.n};Y.prototype.clone=function(){var a=new Y(this.bc),b=U(this).x();a.la=b;a.f=(1|a.f)<<24>>24;W(a,V(this));b=X(this).x();a.ka=b;a.f=(4|a.f)<<24>>24;Ee(a,De(this));Ge(a,Fe(this));return a};
Y.prototype.$classData=C({$b:0},"org.nlogo.tortoise.engine.MersenneTwisterFast",{$b:1,oe:1,c:1,d:1,Yc:1,Ja:1});function hc(){Dd(this)}hc.prototype=new Gd;hc.prototype.constructor=hc;hc.prototype.$classData=C({Gd:0},"scala.collection.Iterable$",{Gd:1,S:1,O:1,c:1,T:1,P:1});var gc;function Vb(){}Vb.prototype=new te;Vb.prototype.constructor=Vb;Vb.prototype.C=function(){return!1};Vb.prototype.J=function(){throw new Ce("next on empty iterator");};
Vb.prototype.$classData=C({Id:0},"scala.collection.Iterator$$anon$2",{Id:1,Jb:1,c:1,Qb:1,ga:1,ea:1});function Ke(a){this.Ld=a}Ke.prototype=new te;Ke.prototype.constructor=Ke;Ke.prototype.C=function(){return!this.Ld.m()};Ke.prototype.J=function(){if(this.C())Wd();else return Wb().fa.J()};Ke.prototype.$classData=C({Kd:0},"scala.collection.LinearSeqLike$$anon$1",{Kd:1,Jb:1,c:1,Qb:1,ga:1,ea:1});function fc(){Dd(this);ec=this;new Uc}fc.prototype=new Gd;fc.prototype.constructor=fc;
fc.prototype.$classData=C({Pd:0},"scala.collection.Traversable$",{Pd:1,S:1,O:1,c:1,T:1,P:1});var ec;function Le(){}Le.prototype=new ve;Le.prototype.constructor=Le;function Me(){}Me.prototype=Le.prototype;class Vc extends md{constructor(){super();I(this,null)}Ha(){qe||(qe=new pe);return qe.rd?md.prototype.Ha.call(this):this}}Vc.prototype.$classData=C({od:0},"scala.util.control.BreakControl",{od:1,s:1,c:1,d:1,ze:1,Ae:1});function va(a){return Ra(Sa(),a)}
var na=C({nc:0},"java.lang.Double",{nc:1,da:1,c:1,d:1,D:1,F:1,pa:1},a=>"number"===typeof a),ma=C({pc:0},"java.lang.Float",{pc:1,da:1,c:1,d:1,D:1,F:1,pa:1},a=>la(a)),ka=C({tc:0},"java.lang.Integer",{tc:1,da:1,c:1,d:1,D:1,F:1,pa:1},a=>ha(a)),qa=C({vc:0},"java.lang.Long",{vc:1,da:1,c:1,d:1,D:1,F:1,pa:1},a=>a instanceof p);class ed extends ye{constructor(a){super();I(this,a)}}ed.prototype.$classData=C({xc:0},"java.lang.NumberFormatException",{xc:1,Ka:1,z:1,E:1,s:1,c:1,d:1});
function bb(a,b){return a.codePointAt(b)|0}function u(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}var fa=C({ec:0},"java.lang.String",{ec:1,c:1,d:1,D:1,mb:1,F:1,pa:1},a=>"string"===typeof a);
class $a extends ye{constructor(a,b,c){super();this.Rc=a;this.Tc=b;this.Sc=c;I(this,null)}Ia(){var a=this.Sc,b=this.Tc,c=this.Rc+(0>a?"":" near index "+a)+"\n"+b;if(0<=a&&null!==b&&a<b.length){if(0>a)throw c=new ye,I(c,null),c;a=" ".repeat(a);c=c+"\n"+a+"^"}return c}}$a.prototype.$classData=C({Qc:0},"java.util.regex.PatternSyntaxException",{Qc:1,Ka:1,z:1,E:1,s:1,c:1,d:1});function Ne(){}Ne.prototype=new le;Ne.prototype.constructor=Ne;function Oe(){}Oe.prototype=Ne.prototype;
function he(){ge=this;new Cd(this)}he.prototype=new Me;he.prototype.constructor=he;he.prototype.$classData=C({ae:0},"scala.collection.immutable.Set$",{ae:1,Me:1,Oe:1,Je:1,O:1,c:1,P:1});var ge;function jc(){Dd(this)}jc.prototype=new Oe;jc.prototype.constructor=jc;jc.prototype.$classData=C({Nd:0},"scala.collection.Seq$",{Nd:1,Ca:1,Ba:1,S:1,O:1,c:1,T:1,P:1});var ic;
function Pe(a){a=ea(a.Hb()).ba.name;for(var b=-1+a.length|0;;)if(-1!==b&&36===a.charCodeAt(b))b=-1+b|0;else break;if(-1===b||46===a.charCodeAt(b))return"";for(var c="";;){for(var d=1+b|0;;)if(-1!==b&&57>=a.charCodeAt(b)&&48<=a.charCodeAt(b))b=-1+b|0;else break;for(var e=b;;)if(-1!==b&&36!==a.charCodeAt(b)&&46!==a.charCodeAt(b))b=-1+b|0;else break;var f=1+b|0;if(b===e&&d!==a.length)return c;for(;;)if(-1!==b&&36===a.charCodeAt(b))b=-1+b|0;else break;e=-1===b?!0:46===a.charCodeAt(b);var g;(g=e)||(g=
a.charCodeAt(f),g=!(90<g&&127>g||65>g));if(g&&(d=a.substring(f,d),c=""===c?d:d+"."+c,e))return c}}function Qe(){}Qe.prototype=new Oe;Qe.prototype.constructor=Qe;function Re(){}Re.prototype=Qe.prototype;
class N extends T{constructor(a){super();this.Ua=a;I(this,a)}Gb(){return"UninitializedFieldError"}Eb(){return 1}Fb(a){if(0===a)return this.Ua;throw new ze(""+a);}y(){Ud();var a=this.Eb();if(0===a)a=u(this.Gb());else{for(var b=-889275714,c=0;c<a;){var d=this.Fb(c);b=Zc(b,Rc(Tc(),d));c=1+c|0}a=Wc(b^a)}return a}B(a){return this===a?!0:a instanceof N?this.Ua===a.Ua:!1}}N.prototype.$classData=C({bd:0},"scala.UninitializedFieldError",{bd:1,z:1,E:1,s:1,c:1,d:1,ad:1,K:1,o:1});function lc(){Dd(this)}
lc.prototype=new Re;lc.prototype.constructor=lc;lc.prototype.$classData=C({Bd:0},"scala.collection.IndexedSeq$",{Bd:1,Xd:1,Ca:1,Ba:1,S:1,O:1,c:1,T:1,P:1});var kc;function Se(a,b,c){this.R=0;this.Nb=null;this.Ob=c;if(null===a)throw null;this.Nb=a;this.R=b}Se.prototype=new te;Se.prototype.constructor=Se;Se.prototype.C=function(){return this.R<this.Ob};Se.prototype.J=function(){this.R>=this.Ob&&Wb().fa.J();var a=this.Nb.V(this.R);this.R=1+this.R|0;return a};
Se.prototype.$classData=C({Dd:0},"scala.collection.IndexedSeqLike$Elements",{Dd:1,Jb:1,c:1,Qb:1,ga:1,ea:1,Ce:1,o:1,d:1});function xe(){}xe.prototype=new v;xe.prototype.constructor=xe;xe.prototype.$classData=C({ed:0},"scala.math.Ordering$Int$",{ed:1,c:1,xe:1,we:1,ne:1,ye:1,ue:1,o:1,d:1});var we;function Te(){}Te.prototype=new v;Te.prototype.constructor=Te;function Ue(){}Ue.prototype=Te.prototype;function nc(){Dd(this);mc=this}nc.prototype=new Oe;nc.prototype.constructor=nc;
nc.prototype.$classData=C({Yd:0},"scala.collection.immutable.List$",{Yd:1,Ca:1,Ba:1,S:1,O:1,c:1,T:1,P:1,o:1,d:1});var mc;function Ve(){Dd(this);We=this;new oe}Ve.prototype=new Oe;Ve.prototype.constructor=Ve;Ve.prototype.$classData=C({be:0},"scala.collection.immutable.Stream$",{be:1,Ca:1,Ba:1,S:1,O:1,c:1,T:1,P:1,o:1,d:1});var We;function oc(){We||(We=new Ve);return We}function Xe(){this.Q=null}Xe.prototype=new Ue;Xe.prototype.constructor=Xe;function Ye(){}Ye.prototype=Xe.prototype;Xe.prototype.r=function(){return this.Q};
Xe.prototype.B=function(a){return this===a};Xe.prototype.y=function(){return Ba(this)};function Ze(a,b){if(a===b)return!0;if(b&&b.$classData&&b.$classData.p.De&&a&&a.$classData&&a.$classData.p.Ee)return a.ie()===b.ie()&&a.df(b);a=a.aa();for(b=b.aa();a.C()&&b.C();)if(!Kc(Pc(),a.J(),b.J()))return!1;return!a.C()&&!b.C()}function qc(){Dd(this);pc=this}qc.prototype=new Re;qc.prototype.constructor=qc;
qc.prototype.$classData=C({ge:0},"scala.collection.immutable.Vector$",{ge:1,Xd:1,Ca:1,Ba:1,S:1,O:1,c:1,T:1,P:1,o:1,d:1});var pc;function wc(){this.Q="Any"}wc.prototype=new Ye;wc.prototype.constructor=wc;wc.prototype.$classData=C({id:0},"scala.reflect.ManifestFactory$AnyManifest$",{id:1,wa:1,va:1,c:1,ua:1,ta:1,sa:1,xa:1,o:1,d:1,K:1});var vc;function Ac(){this.Q="AnyVal"}Ac.prototype=new Ye;Ac.prototype.constructor=Ac;
Ac.prototype.$classData=C({jd:0},"scala.reflect.ManifestFactory$AnyValManifest$",{jd:1,wa:1,va:1,c:1,ua:1,ta:1,sa:1,xa:1,o:1,d:1,K:1});var zc;function Cc(){this.Q="Nothing"}Cc.prototype=new Ye;Cc.prototype.constructor=Cc;Cc.prototype.$classData=C({kd:0},"scala.reflect.ManifestFactory$NothingManifest$",{kd:1,wa:1,va:1,c:1,ua:1,ta:1,sa:1,xa:1,o:1,d:1,K:1});var Bc;function Ec(){this.Q="Null"}Ec.prototype=new Ye;Ec.prototype.constructor=Ec;
Ec.prototype.$classData=C({ld:0},"scala.reflect.ManifestFactory$NullManifest$",{ld:1,wa:1,va:1,c:1,ua:1,ta:1,sa:1,xa:1,o:1,d:1,K:1});var Dc;function yc(){this.Q="Object"}yc.prototype=new Ye;yc.prototype.constructor=yc;yc.prototype.$classData=C({md:0},"scala.reflect.ManifestFactory$ObjectManifest$",{md:1,wa:1,va:1,c:1,ua:1,ta:1,sa:1,xa:1,o:1,d:1,K:1});var xc;function $e(){}$e.prototype=new v;$e.prototype.constructor=$e;function af(){}af.prototype=$e.prototype;$e.prototype.Hb=function(){return this};
$e.prototype.cb=function(){return Pe(this)};function bf(a){return 0===a.v()?Wb().fa:new Se(a,0,a.v())}function cf(a,b){for(var c=0,d=a.v();c<d;)b.H(a.V(c)),c=1+c|0}function df(a,b){if(b&&b.$classData&&b.$classData.p.Ad){var c=a.v();if(c===b.v()){for(var d=0;d<c&&Kc(Pc(),a.V(d),b.V(d));)d=1+d|0;return d===c}return!1}return Ze(a,b)}function ef(){}ef.prototype=new af;ef.prototype.constructor=ef;function ff(){}ff.prototype=ef.prototype;ef.prototype.M=function(a){for(var b=this.aa();b.C();)a.H(b.J())};
ef.prototype.Aa=function(a){return Ze(this,a)};function Z(a){this.w=a}Z.prototype=new v;Z.prototype.constructor=Z;h=Z.prototype;h.m=function(){return 0===this.v()};h.M=function(a){cf(this,a)};h.Aa=function(a){return df(this,a)};h.Ta=function(a){return this.v()-a|0};h.aa=function(){return bf(this)};h.cb=function(){return Pe(this)};h.r=function(){return this.w};h.v=function(){return this.w.length};h.y=function(){return u(this.w)};
h.B=function(a){bc||(bc=new ac);return a instanceof Z?this.w===(null===a?null:a.w):!1};h.V=function(a){return new l(this.w.charCodeAt(a))};h.Hb=function(){return this.w};h.$classData=C({ee:0},"scala.collection.immutable.StringOps",{ee:1,c:1,de:1,Ed:1,Cd:1,Sb:1,Pb:1,K:1,Tb:1,Wb:1,Vb:1,ga:1,ea:1,Mb:1,Rb:1,Kb:1,Lb:1,cd:1,D:1});function hf(){}hf.prototype=new ff;hf.prototype.constructor=hf;function jf(){}jf.prototype=hf.prototype;hf.prototype.m=function(){return 0===this.Ta(0)};
hf.prototype.r=function(){var a=this.cb()+"(",b=new Ie;Je(b,"");je(b,a);this.M(new ie(this,b,", "));je(b,")");return b.A.n};hf.prototype.B=function(a){return a&&a.$classData&&a.$classData.p.$a?a===this||this.Aa(a):!1};function kf(){}kf.prototype=new jf;kf.prototype.constructor=kf;function lf(){}lf.prototype=kf.prototype;function Vd(){}Vd.prototype=new jf;Vd.prototype.constructor=Vd;function mf(){}h=mf.prototype=Vd.prototype;
h.Aa=function(a){if(a&&a.$classData&&a.$classData.p.Jd)if(this===a)var b=!0;else{for(b=this;;){if(b.m()||a.m())c=!1;else{Pc();Wd();var c=Kc(0,void 0,Wd())}if(c)b=nf(),a=nf();else break}b=b.m()&&a.m()}else b=Ze(this,a);return b};h.Ta=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.m()?0:1;break a}if(b.m()){a=-1;break a}c=1+c|0;b=nf()}return a};h.y=function(){return Td(this)};h.aa=function(){return this.m()?Wb().fa:new Ke(this)};h.M=function(a){for(var b=this;!b.m();)a.H(Wd()),b=nf()};
h.cb=function(){return"List"};h.H=function(a){a|=0;for(var b=this,c=a;!b.m()&&0<c;)b=nf(),c=-1+c|0;if(0>a||b.m())throw new ze(""+a);Wd()};function Rd(){}Rd.prototype=new mf;Rd.prototype.constructor=Rd;h=Rd.prototype;h.m=function(){return!0};function Wd(){throw new Ce("head of empty list");}function nf(){throw new Be;}h.B=function(a){return a&&a.$classData&&a.$classData.p.$a?a.m():!1};h.Gb=function(){return"Nil"};h.Eb=function(){return 0};h.Fb=function(a){throw new ze(""+a);};
h.$classData=C({$d:0},"scala.collection.immutable.Nil$",{$d:1,Re:1,wd:1,vd:1,xd:1,c:1,Od:1,Tb:1,Wb:1,Vb:1,ga:1,ea:1,Mb:1,Rb:1,zd:1,Wd:1,Fd:1,yd:1,Kb:1,Pb:1,K:1,Md:1,Zc:1,ha:1,$a:1,Lb:1,Sb:1,Qe:1,Se:1,Pe:1,Te:1,re:1,Jd:1,Fe:1,ad:1,Ge:1,o:1,d:1});var Pd;function Je(a,b){var c=b.length+16|0,d=new re;d.n="";if(0>c)throw new Ae;d.n=""+d.n+b;a.A=d}function Ie(){this.A=null}Ie.prototype=new lf;Ie.prototype.constructor=Ie;h=Ie.prototype;h.M=function(a){cf(this,a)};h.Aa=function(a){return df(this,a)};
h.Ta=function(a){return this.v()-a|0};h.y=function(){return Td(this)};h.aa=function(){return bf(this)};h.v=function(){return this.A.v()};function je(a,b){a=a.A;a.n=""+a.n+b}h.r=function(){return this.A.n};h.m=function(){return 0===this.A.v()};h.H=function(a){this.A.n.charCodeAt(a|0)};h.V=function(a){return new l(this.A.n.charCodeAt(a))};
h.$classData=C({he:0},"scala.collection.mutable.StringBuilder",{he:1,Ue:1,wd:1,vd:1,xd:1,c:1,Od:1,Tb:1,Wb:1,Vb:1,ga:1,ea:1,Mb:1,Rb:1,zd:1,Wd:1,Fd:1,yd:1,Kb:1,Pb:1,K:1,Md:1,Zc:1,ha:1,$a:1,Lb:1,Sb:1,af:1,Ze:1,cf:1,te:1,bf:1,We:1,Yc:1,Ja:1,mb:1,Xe:1,Ad:1,Cd:1,Ye:1,de:1,Ed:1,cd:1,D:1,$e:1,Ve:1,Ke:1,He:1,o:1,d:1});aa=new p(0,0);Oa.Yb=aa;MersenneTwisterFast=function(...a){if(void 0===a[0]){L();a=H();Ua||(Ua=new Ta);var b=1E6*+(0,Ua.rb)();b=Ob(a,b);a=new p(b,a.k)}else a=q(a[0]);return new Y(new p(a.i,a.l))};
}).call(this);

window.RNG = new MersenneTwisterFast();
